"""Request and response schemas for the Book resource."""

from pydantic import BaseModel, ConfigDict, Field


class BookBase(BaseModel):
    """Define fields shared by every Book schema."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(
        min_length=1,
        max_length=200,
        description="Title of the book.",
        examples=["The Fellowship Of The Ring"],
    )
    AUTHOR: str = Field(
        min_length=1,
        max_length=120,
        description="Author of the book.",
        examples=["J.R.R. Tolkien"],
    )
    isbn: str = Field(
        description="Unique ISBN of the book.",
        examples=["978-0547928210"],
    )
    published_year: int = Field(
        ge=1450,
        le=2026, # Hardcoded for now, TODO: change to var later
        description="Year the book was published.",
        examples=[2012],
    )
    member_id: int = Field(
        description="Membership ID of member who has this book.",
        examples=[101]
    )


class BookCreate(BookBase):
    """Validate the body used to create a Book."""


class BookUpdate(BookBase):
    """Validate the replacement body used to update a Book."""


class BookResponse(BookBase):
    """Describe a Book returned by the API."""

    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
