"""Request and response schemas for the Member resource."""

from pydantic import BaseModel, ConfigDict, Field, EmailStr


class MemberBase(BaseModel):
    """Define fields shared by every Member schema."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=1,
        max_length=120,
        description="Name of the library member.",
        examples=["Izzy Bledsoe"],
    )
    email: EmailStr = Field(
        description="Unique email address of the library member.",
        examples=["ibledsoe1@collin.edu"],
    )
    membership_id: str = Field(
        description="Unique membership ID of the library member.",
        examples="101",
    )
    phone: str = Field(
        min_length=10,
        max_length=10,
        description="Phone number of the library member "
        "(must be 10 digits w/o formatting like dashes and parentheses).",
        examples="1234567890",
    )


class MemberCreate(MemberBase):
    """Validate the body used to create a Member."""


class MemberUpdate(MemberBase):
    """Validate the replacement body used to update a Member."""


class MemberResponse(MemberBase):
    """Describe a Member returned by the API."""

    # Server-generated ID, appears in responses
    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
